#!/usr/bin/env bash
set -x
xhost +local:

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

GRAPHICS_OPTS="\
    --env DISPLAY=$DISPLAY \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
"

DATABASE_OPTS="\
     --volume $DB_TMP_DIR/postgresql:/var/lib/postgresql \
"

PORT_MAPPING_OPTS="\
    -p 5432:5432
"

parse_arguments() {
    COMMAND=""
    while [[ $# -gt 0 ]]; do
        case $1 in
            *)
                COMMAND+="$1 "
            shift;;
        esac
    done
}

run_container() {

    docker run \
        --privileged \
        --name $CONTAINER_NAME \
        --rm \
        --user $CONTAINER_USER \
        --volume $REPO_DIR:$CONTAINER_REPO_DIR \
        --volume ${CONTAINER_PERSISTENT_VOLUME:?}:$CONTAINER_PERSISTENT_DIR \
        --volume $HOME/Desktop:/home/$CONTAINER_USER/Desktop \
        $DATABASE_OPTS \
        $EXTRA_CONTAINER_OPTS \
        $GRAPHICS_OPTS \
        $PORT_MAPPING_OPTS \
        $IMAGE_NAME \
        $COMMAND || exit_on_error
}

parse_arguments $@
run_container $@
